import {
  AlertTriangle,
  ArrowLeftRight,
  ArrowUpDown,
  Banknote,
  CalendarDays,
  CalendarRange,
  ClipboardList,
  History,
  Package,
  Receipt,
  Scale,
  Tags,
  TrendingUp,
  Undo2,
  Wallet,
  Warehouse,
  type LucideIcon,
} from "lucide-react";
import type { ReportCenterIcon } from "@/features/reports/report-center-catalog";

export const REPORT_CENTER_ICON_MAP: Record<ReportCenterIcon, LucideIcon> = {
  "alert-triangle": AlertTriangle,
  "arrow-left-right": ArrowLeftRight,
  "arrow-up-down": ArrowUpDown,
  banknote: Banknote,
  "calendar-days": CalendarDays,
  "calendar-range": CalendarRange,
  "clipboard-list": ClipboardList,
  history: History,
  package: Package,
  receipt: Receipt,
  scale: Scale,
  tags: Tags,
  "trending-up": TrendingUp,
  "undo-2": Undo2,
  wallet: Wallet,
  warehouse: Warehouse,
};
