import type {
  Supplier,
  SupplierPayment,
  SupplierPurchaseOrder,
  SupplierReceiving,
} from "@/features/suppliers/types";

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-lao-bev",
    supplierCode: "SUP-001",
    companyName: "Lao Beverage Supplier",
    contactPerson: "Khamla S.",
    phone: "+856 20 5555 0101",
    email: "orders@laobeverage.local",
    address: "Vientiane Capital, Laos",
    taxNumber: "LAO-TAX-10001",
    creditLimitLak: 25000000,
    openingBalanceLak: 2250000,
    outstandingBalanceLak: 5850000,
    creditTerms: "Net 30",
    averageDeliveryDays: 2.4,
    status: "active",
    notes: "Main drink supplier. Weekly delivery on Monday and Thursday.",
  },
  {
    id: "sup-snack",
    supplierCode: "SUP-002",
    companyName: "Snack Distribution Laos",
    contactPerson: "Anousone P.",
    phone: "+856 20 5555 0202",
    email: "sales@snacklaos.local",
    address: "Sisattanak, Vientiane",
    taxNumber: "LAO-TAX-10002",
    creditLimitLak: 12000000,
    openingBalanceLak: 0,
    outstandingBalanceLak: 2100000,
    creditTerms: "Net 15",
    averageDeliveryDays: 3.1,
    status: "active",
    notes: "Snacks and packaged food supplier with mixed carton units.",
  },
  {
    id: "sup-household",
    supplierCode: "SUP-003",
    companyName: "Household Lao Trade",
    contactPerson: "Vilay K.",
    phone: "+856 20 5555 0303",
    email: "contact@householdlao.local",
    address: "Chanthabouly, Vientiane",
    taxNumber: "LAO-TAX-10003",
    creditLimitLak: 10000000,
    openingBalanceLak: 940000,
    outstandingBalanceLak: 0,
    creditTerms: "Prepaid",
    averageDeliveryDays: 4.8,
    status: "inactive",
    notes: "Inactive supplier retained for filter testing.",
  },
  {
    id: "sup-cold-chain",
    supplierCode: "SUP-004",
    companyName: "Cold Chain Fresh Foods",
    contactPerson: "Maly T.",
    phone: "+856 20 5555 0404",
    email: "fresh@coldchain.local",
    address: "Xaysettha, Vientiane",
    taxNumber: "LAO-TAX-10004",
    creditLimitLak: 18000000,
    openingBalanceLak: 1500000,
    outstandingBalanceLak: 6200000,
    creditTerms: "Net 7",
    averageDeliveryDays: 1.6,
    status: "active",
    notes: "Cold storage supplier. Requires expiry checks during receiving.",
  },
];

export const mockSupplierPurchaseOrders: SupplierPurchaseOrder[] = [
  {
    id: "spo-001",
    supplierId: "sup-lao-bev",
    purchaseNo: "PO-2026-0001",
    purchaseDate: "2026-06-12",
    warehouseName: "Main Store",
    status: "partial",
    totalLak: 5850000,
  },
  {
    id: "spo-002",
    supplierId: "sup-lao-bev",
    purchaseNo: "PO-2026-0005",
    purchaseDate: "2026-06-04",
    warehouseName: "Backroom Warehouse",
    status: "received",
    totalLak: 4300000,
  },
  {
    id: "spo-003",
    supplierId: "sup-snack",
    purchaseNo: "PO-2026-0002",
    purchaseDate: "2026-06-13",
    warehouseName: "Backroom Warehouse",
    status: "ordered",
    totalLak: 2100000,
  },
  {
    id: "spo-004",
    supplierId: "sup-household",
    purchaseNo: "PO-2026-0000",
    purchaseDate: "2026-05-22",
    warehouseName: "Main Store",
    status: "received",
    totalLak: 940000,
  },
  {
    id: "spo-005",
    supplierId: "sup-cold-chain",
    purchaseNo: "PO-2026-0006",
    purchaseDate: "2026-06-14",
    warehouseName: "Cold Storage",
    status: "ordered",
    totalLak: 6200000,
  },
];

export const mockSupplierReceivings: SupplierReceiving[] = [
  {
    id: "rec-001",
    supplierId: "sup-lao-bev",
    receiveNo: "GR-2026-0001",
    purchaseNo: "PO-2026-0001",
    receivedDate: "2026-06-13",
    warehouseName: "Main Store",
    itemCount: 2,
    status: "partial",
  },
  {
    id: "rec-002",
    supplierId: "sup-lao-bev",
    receiveNo: "GR-2026-0004",
    purchaseNo: "PO-2026-0005",
    receivedDate: "2026-06-05",
    warehouseName: "Backroom Warehouse",
    itemCount: 3,
    status: "received",
  },
  {
    id: "rec-003",
    supplierId: "sup-household",
    receiveNo: "GR-2026-0000",
    purchaseNo: "PO-2026-0000",
    receivedDate: "2026-05-23",
    warehouseName: "Main Store",
    itemCount: 1,
    status: "received",
  },
  {
    id: "rec-004",
    supplierId: "sup-cold-chain",
    receiveNo: "GR-2026-0006",
    purchaseNo: "PO-2026-0006",
    receivedDate: "2026-06-14",
    warehouseName: "Cold Storage",
    itemCount: 4,
    status: "partial",
  },
];

export const mockSupplierPayments: SupplierPayment[] = [
  {
    id: "sppay-001",
    supplierId: "sup-lao-bev",
    paymentNo: "SPAY-2026-0001",
    paymentDate: "2026-06-12",
    method: "bank",
    amountLak: 2250000,
    note: "Partial payment for beverage credit",
  },
  {
    id: "sppay-002",
    supplierId: "sup-household",
    paymentNo: "SPAY-2026-0002",
    paymentDate: "2026-06-01",
    method: "cash",
    amountLak: 940000,
    note: "Settled old balance",
  },
  {
    id: "sppay-003",
    supplierId: "sup-cold-chain",
    paymentNo: "SPAY-2026-0003",
    paymentDate: "2026-06-14",
    method: "qr",
    amountLak: 1500000,
    note: "Deposit for cold goods",
  },
];
