export const DemoStorageKeys = {
  auditLogs: "ego.pos.auditLogs",
  categories: "ego.pos.categories",
  companyLogoUrl: "ego-pos:company-logo-url",
  customerDisplayQr: "ego.pos.customerDisplay.qr",
  customerDisplayQrCatalog: "ego.pos.customerDisplay.qrCatalog",
  customerDisplaySettings: "ego.pos.customerDisplay.settings",
  customerDisplayState: "ego.pos.customerDisplay.state",
  customers: "ego.pos.customers",
  inventoryMovements: "ego.pos.inventory.movements",
  locale: "ego-pos:locale",
  memberships: "ego.pos.memberships",
  onboardingBusiness: "ego-pos:onboarding-business",
  onboardingComplete: "ego-pos:onboarding-complete",
  onboardingDraft: "ego-pos:onboarding-draft",
  onboardingTemplate: "ego-pos:onboarding-template",
  pendingApprovals: "ego.pos.pendingApprovals",
  planDaysLeft: "ego-pos:plan-days-left",
  planName: "ego-pos:plan-name",
  products: "ego.pos.products",
  promotions: "ego.pos.promotions",
  qrAccounts: "ego.pos.qr.accounts",
  qrBanks: "ego.pos.qr.banks",
  receipts: "ego.pos.receipts",
  sales: "ego.pos.sales",
  settings: "ego.pos.settings",
  staffAudit: "ego.pos.staff.access.audit",
  staffUsers: "ego.pos.staff.access.users",
  theme: "ego-pos:theme",
} as const;

export const LegacyStorageKeys = {
  companyLogoUrl: ["ui.ego.pos.company.logo.url"],
  customerDisplaySettings: ["ego-pos:customer-display-settings"],
  customerDisplayState: ["ui.ego.pos.customer.display.state"],
  locale: ["ui.ego.pos.locale"],
  onboardingBusiness: ["igo-pos:onboarding-business"],
  onboardingComplete: ["igo-pos:onboarding-complete"],
  onboardingDraft: ["igo-pos:onboarding-draft"],
  onboardingTemplate: ["igo-pos:onboarding-template"],
  qrAccounts: ["ui.ego.pos.dynamic.qr.accounts"],
  qrBanks: ["ui.ego.pos.qr.banks", "ui.ego.pos.dynamic.qr.banks"],
  theme: ["igo-theme"],
} as const;

export type DemoStorageKey = (typeof DemoStorageKeys)[keyof typeof DemoStorageKeys];
