import type { Category, MockProductImage, Product } from "@/features/products/types";

export const mockCategories: Category[] = [
  {
    id: "cat-drinks",
    nameLo: "Drinks",
    nameEn: "Drinks",
    productCount: 128,
    status: "active",
  },
  {
    id: "cat-snacks",
    nameLo: "Snacks",
    nameEn: "Snacks",
    productCount: 94,
    status: "active",
  },
  {
    id: "cat-household",
    nameLo: "Household",
    nameEn: "Household",
    productCount: 41,
    status: "active",
  },
  {
    id: "cat-tobacco",
    nameLo: "Tobacco",
    nameEn: "Tobacco",
    productCount: 16,
    status: "inactive",
  },
];

export const mockProducts: Product[] = [
  {
    id: "prd-pepsi-can",
    productCode: "P-0001",
    barcode: "8858998580011",
    sku: "DRK-PEP-CAN-001",
    nameLo: "Pepsi Can",
    nameEn: "Pepsi Can",
    categoryId: "cat-drinks",
    categoryName: "Drinks",
    supplierName: "Lao Beverage Supplier",
    brandName: "Pepsi",
    description: "Carbonated soft drink for chilled display and quick barcode sales.",
    tags: ["drink", "can", "cold"],
    costPriceLak: 5500,
    currentStock: 18,
    expiryDate: "2026-08-18",
    sellingPriceLak: 8000,
    minStock: 24,
    targetStock: 48,
    reorderQtyMode: "AUTO",
    status: "active",
    updatedAt: "2026-06-10",
    units: [
      {
        id: "unit-pepsi-can",
        unitName: "Can",
        conversionQty: 1,
        barcode: "8858998580011",
        sellingPriceLak: 8000,
        isBaseUnit: true,
      },
      {
        id: "unit-pepsi-pack",
        unitName: "Pack",
        conversionQty: 6,
        barcode: "8858998580066",
        sellingPriceLak: 45000,
        isBaseUnit: false,
      },
      {
        id: "unit-pepsi-carton",
        unitName: "Carton",
        conversionQty: 24,
        barcode: "8858998580240",
        sellingPriceLak: 168000,
        isBaseUnit: false,
      },
    ],
  },
  {
    id: "prd-water-bottle",
    productCode: "P-0002",
    barcode: "8851959132015",
    sku: "DRK-WAT-BTL-500",
    nameLo: "Drinking Water 500ml",
    nameEn: "Drinking Water 500ml",
    categoryId: "cat-drinks",
    categoryName: "Drinks",
    supplierName: "Local Supplier",
    brandName: "House Brand",
    description: "Everyday bottled water sold by bottle and pack.",
    tags: ["water", "drink", "essential"],
    costPriceLak: 1800,
    currentStock: 126,
    expiryDate: "2027-01-04",
    sellingPriceLak: 3000,
    minStock: 48,
    targetStock: 120,
    reorderQtyMode: "AUTO",
    status: "active",
    updatedAt: "2026-06-09",
    units: [
      {
        id: "unit-water-bottle",
        unitName: "Bottle",
        conversionQty: 1,
        barcode: "8851959132015",
        sellingPriceLak: 3000,
        isBaseUnit: true,
      },
      {
        id: "unit-water-pack",
        unitName: "Pack",
        conversionQty: 12,
        barcode: "8851959132121",
        sellingPriceLak: 33000,
        isBaseUnit: false,
      },
    ],
  },
  {
    id: "prd-lays-classic",
    productCode: "P-0003",
    barcode: "8850718811220",
    sku: "SNK-LAY-CLS-050",
    nameLo: "Lay's Classic",
    nameEn: "Lay's Classic",
    categoryId: "cat-snacks",
    categoryName: "Snacks",
    supplierName: "Snack Distribution Laos",
    brandName: "Lay's",
    description: "Snack product prepared for shelf display.",
    tags: ["snack", "chips"],
    costPriceLak: 6500,
    currentStock: 4,
    expiryDate: "2026-07-02",
    sellingPriceLak: 10000,
    minStock: 20,
    targetStock: 40,
    reorderQtyMode: "MANUAL",
    status: "draft",
    updatedAt: "2026-06-08",
    units: [
      {
        id: "unit-lays-bag",
        unitName: "Bag",
        conversionQty: 1,
        barcode: "8850718811220",
        sellingPriceLak: 10000,
        isBaseUnit: true,
      },
    ],
  },
  {
    id: "prd-dish-soap",
    productCode: "P-0004",
    barcode: "8850006330181",
    sku: "HOU-SOAP-500",
    nameLo: "Dishwashing Liquid",
    nameEn: "Dishwashing Liquid",
    categoryId: "cat-household",
    categoryName: "Household",
    supplierName: "Household Lao Trade",
    brandName: "Sunlight",
    description: "Household cleaning product with carton conversion.",
    tags: ["household", "cleaning"],
    costPriceLak: 11000,
    currentStock: 0,
    sellingPriceLak: 16000,
    minStock: 12,
    targetStock: 24,
    reorderQtyMode: "AUTO",
    status: "inactive",
    updatedAt: "2026-06-07",
    units: [
      {
        id: "unit-soap-bottle",
        unitName: "Bottle",
        conversionQty: 1,
        barcode: "8850006330181",
        sellingPriceLak: 16000,
        isBaseUnit: true,
      },
      {
        id: "unit-soap-carton",
        unitName: "Carton",
        conversionQty: 12,
        barcode: "8850006330120",
        sellingPriceLak: 180000,
        isBaseUnit: false,
      },
    ],
  },
];

export const mockProductImages: MockProductImage[] = [
  {
    id: "img-pepsi",
    title: "Pepsi Can",
    keyword: "pepsi drink soda can",
    color: "from-cyan-500 to-blue-700",
  },
  {
    id: "img-water",
    title: "Water Bottle",
    keyword: "water bottle drink",
    color: "from-sky-300 to-cyan-600",
  },
  {
    id: "img-snack",
    title: "Snack Bag",
    keyword: "chips snack lays bag",
    color: "from-yellow-300 to-orange-600",
  },
  {
    id: "img-soap",
    title: "Dish Soap",
    keyword: "soap household cleaning",
    color: "from-emerald-300 to-green-700",
  },
  {
    id: "img-carton",
    title: "Carton Pack",
    keyword: "carton pack wholesale",
    color: "from-purple-400 to-fuchsia-700",
  },
  {
    id: "img-generic",
    title: "Generic Product",
    keyword: "product store grocery",
    color: "from-slate-400 to-slate-700",
  },
];
