#!/usr/bin/env bash
# Cloud Agent install script for EGO POS.
# Idempotent: safe to run repeatedly. Prepares PostgreSQL, Node dependencies,
# the Prisma client, the database schema, and seed data for local development.
set -euo pipefail

cd "$(dirname "$0")/.."

PG_VERSION=16

echo "[install] Ensuring PostgreSQL is installed..."
if ! command -v pg_ctlcluster >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
fi

echo "[install] Starting PostgreSQL cluster ${PG_VERSION}/main..."
sudo pg_ctlcluster "${PG_VERSION}" main start 2>/dev/null || true
for _ in $(seq 1 30); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done

echo "[install] Ensuring postgres role password and development databases..."
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" >/dev/null
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='igo_pos'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE igo_pos;" >/dev/null
sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='igo_pos_test'" | grep -q 1 \
  || sudo -u postgres psql -c "CREATE DATABASE igo_pos_test;" >/dev/null

echo "[install] Writing .env.local (if missing)..."
if [ ! -f .env.local ]; then
  SECRET="$(openssl rand -hex 32 2>/dev/null || echo dev-local-insecure-secret-change-me)"
  cat > .env.local <<EOF
# Generated by .cursor/install.sh for local Cloud Agent development.
# Never point these at Production.
DEV_DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/igo_pos?schema=public"
TEST_DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/igo_pos_test?schema=public"
DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/igo_pos?schema=public"
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="${SECRET}"
IGO_DEFAULT_LOCALE="lo"
IGO_BASE_CURRENCY="LAK"
IGO_DEMO_MODE="false"
EOF
fi

echo "[install] Installing npm dependencies..."
# --force is required because package.json lists the Windows-only
# @next/swc-win32-x64-msvc package as a hard dependency, which fails the
# platform check on Linux without it.
npm install --force

echo "[install] Generating Prisma client..."
npm run prisma:generate

echo "[install] Syncing database schema (prisma db push)..."
npx prisma db push

echo "[install] Seeding database..."
npm run db:seed

echo "[install] Complete."
