export const phase13SeedStrategy = {
  order: [
    "Plan",
    "User",
    "Company",
    "Branch",
    "Warehouse",
    "Role",
    "Permission",
    "MembershipLevel",
    "Supplier",
    "Category",
    "Brand",
    "Product",
    "ProductUnit",
    "ProductImage",
    "InventoryBalance",
    "InventoryLot",
    "StockMovement",
    "Customer",
    "LoyaltyPointLedger",
    "CustomerPayment",
    "Purchase",
    "PurchaseItem",
    "GoodsReceipt",
    "GoodsReceiptItem",
    "SupplierPayable",
    "Promotion",
    "PromotionProduct",
    "PromotionCategory",
    "PromotionMembershipLevel",
  ],
  defaults: {
    baseCurrency: "LAK",
    branchId: "gobox-main-branch",
    companyId: "gobox-company",
    defaultLocale: "lo",
    ownerUsername: "owner",
    warehouseId: "gobox-default-warehouse",
  },
  notes: [
    "Use upsert for stable foundation records and createMany with skipDuplicates for sample catalog rows.",
    "Resolve UI labels to foreign keys before writes: brandId, supplierId, membershipLevelId, and promotionType.",
    "Store mixed POS payment as more than one SalePayment row, usually cash plus qr.",
    "Seed inventory quantities through InventoryBalance plus InventoryLot, then add StockMovement audit rows.",
    "Keep demo mock data untouched until Prisma-backed services are verified against a migrated database.",
  ],
} as const;
