// TEST/DEMO ARTIFACT ONLY (B7-4): not used by any runtime read path.
// Runtime purchasing reads come exclusively from PostgreSQL via Prisma
// (features/purchasing/prisma-repository.ts). Retained for verification
// harnesses/local demos; do not wire into production services.
import type {
  PurchaseOrder,
  Supplier,
  SupplierPayable,
} from "@/features/purchasing/types";

export const mockSuppliers: Supplier[] = [
  {
    id: "sup-lao-bev",
    supplierCode: "SUP-001",
    name: "Lao Beverage Supplier",
    phone: "+856 20 5555 0101",
    email: "orders@laobeverage.local",
    address: "Vientiane Capital, Laos",
    note: "Main drink supplier. Weekly delivery.",
    creditLimitLak: 25000000,
    outstandingBalanceLak: 5850000,
    status: "active",
  },
  {
    id: "sup-snack",
    supplierCode: "SUP-002",
    name: "Snack Distribution Laos",
    phone: "+856 20 5555 0202",
    email: "sales@snacklaos.local",
    address: "Sisattanak, Vientiane",
    note: "Snacks and packaged food.",
    creditLimitLak: 12000000,
    outstandingBalanceLak: 2100000,
    status: "active",
  },
  {
    id: "sup-household",
    supplierCode: "SUP-003",
    name: "Household Lao Trade",
    phone: "+856 20 5555 0303",
    email: "contact@householdlao.local",
    address: "Chanthabouly, Vientiane",
    note: "Household and cleaning products.",
    creditLimitLak: 10000000,
    outstandingBalanceLak: 0,
    status: "inactive",
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: "po-001",
    purchaseNo: "PO-2026-0001",
    supplierId: "sup-lao-bev",
    supplierName: "Lao Beverage Supplier",
    warehouseId: "wh-main",
    warehouseName: "Main Store",
    currency: "THB",
    exchangeRate: 750,
    subtotal: 7800,
    paidAmount: 3000,
    balanceAmount: 4800,
    status: "partial",
    purchaseDate: "2026-06-12",
    items: [
      {
        id: "poi-001",
        productId: "prd-pepsi-can",
        productName: "Pepsi Can",
        sku: "DRK-PEP-CAN-001",
        barcode: "8858998580011",
        unitName: "Carton",
        quantity: 10,
        receivedQuantity: 6,
        unitCost: 420,
        lotNumber: "LOT-PEP-0612",
        expiryDate: "2026-09-30",
      },
      {
        id: "poi-002",
        productId: "prd-water-bottle",
        productName: "Drinking Water 500ml",
        sku: "DRK-WAT-BTL-500",
        barcode: "8851959132015",
        unitName: "Pack",
        quantity: 20,
        receivedQuantity: 20,
        unitCost: 180,
        lotNumber: "LOT-WAT-0612",
        expiryDate: "2027-02-01",
      },
    ],
  },
  {
    id: "po-002",
    purchaseNo: "PO-2026-0002",
    supplierId: "sup-snack",
    supplierName: "Snack Distribution Laos",
    warehouseId: "wh-backroom",
    warehouseName: "Backroom Warehouse",
    currency: "LAK",
    exchangeRate: 1,
    subtotal: 2100000,
    paidAmount: 0,
    balanceAmount: 2100000,
    status: "ordered",
    purchaseDate: "2026-06-13",
    items: [
      {
        id: "poi-003",
        productId: "prd-lays-classic",
        productName: "Lay's Classic",
        sku: "SNK-LAY-CLS-050",
        barcode: "8850718811220",
        unitName: "Bag",
        quantity: 210,
        receivedQuantity: 0,
        unitCost: 10000,
        lotNumber: "LOT-LAY-0613",
        expiryDate: "2026-11-15",
      },
    ],
  },
];

export const mockSupplierPayables: SupplierPayable[] = [
  {
    id: "pay-001",
    supplierId: "sup-lao-bev",
    supplierName: "Lao Beverage Supplier",
    purchaseNo: "PO-2026-0001",
    totalAmountLak: 5850000,
    paidAmountLak: 2250000,
    balanceAmountLak: 3600000,
    dueDate: "2026-06-25",
    status: "partial",
  },
  {
    id: "pay-002",
    supplierId: "sup-snack",
    supplierName: "Snack Distribution Laos",
    purchaseNo: "PO-2026-0002",
    totalAmountLak: 2100000,
    paidAmountLak: 0,
    balanceAmountLak: 2100000,
    dueDate: "2026-06-28",
    status: "unpaid",
  },
  {
    id: "pay-003",
    supplierId: "sup-household",
    supplierName: "Household Lao Trade",
    purchaseNo: "PO-2026-0000",
    totalAmountLak: 940000,
    paidAmountLak: 940000,
    balanceAmountLak: 0,
    dueDate: "2026-06-01",
    status: "paid",
  },
];
