// TEST/DEMO ARTIFACT ONLY (B7-4): not used by any runtime read path.
// Runtime inventory reads come exclusively from PostgreSQL via Prisma
// (features/inventory/prisma-repository.ts). Retained for verification
// harnesses/local demos; do not wire into production services.
import type { InventoryItem, StockMovement, Warehouse } from "@/features/inventory/types";

export const mockWarehouses: Warehouse[] = [
  {
    id: "wh-main",
    name: "Main Store",
    branchName: "Main Branch",
    type: "store",
  },
  {
    id: "wh-backroom",
    name: "Backroom Warehouse",
    branchName: "Main Branch",
    type: "stockroom",
  },
  {
    id: "wh-cold",
    name: "Cold Storage",
    branchName: "Main Branch",
    type: "distribution",
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: "inv-pepsi-main",
    productId: "prd-pepsi-can",
    warehouseId: "wh-main",
    imageKey: "pepsi",
    productNameLo: "ເປບຊີ ກະປ໋ອງ",
    productNameEn: "Pepsi Can",
    barcode: "8858998580011",
    sku: "DRK-PEP-CAN-001",
    category: "Drinks",
    baseUnit: "Can",
    quantity: 18,
    inventoryValueLak: 81000,
    lastPurchaseDate: "2026-06-15",
    productCode: "P-0001",
    supplierName: "Pepsi Laos",
    unitsSold30Days: 1980,
    units: [
      { barcode: "8858998580011", conversionQty: 1, costPriceLak: 4500, id: "unit-pepsi-can", isBaseUnit: true, isPurchaseUnit: true, status: "active", unitName: "Can" },
      { barcode: "", conversionQty: 24, costPriceLak: 108000, id: "unit-pepsi-carton", isBaseUnit: false, isPurchaseUnit: true, status: "active", unitName: "Carton" },
    ],
    minStock: 24,
    expiryDate: "2026-08-18",
    lastMovementAt: "2026-06-12",
    daysWithoutSale: 2,
  },
  {
    id: "inv-water-main",
    productId: "prd-water-bottle",
    warehouseId: "wh-main",
    imageKey: "water",
    productNameLo: "ນ້ຳດື່ມ 500ml",
    productNameEn: "Drinking Water 500ml",
    barcode: "8851959132015",
    sku: "DRK-WAT-BTL-500",
    category: "Drinks",
    baseUnit: "Bottle",
    quantity: 126,
    inventoryValueLak: 441000,
    lastPurchaseDate: "2026-06-15",
    productCode: "P-0002",
    supplierName: "ABC Trading",
    unitsSold30Days: 2850,
    units: [
      { barcode: "8851959132015", conversionQty: 1, costPriceLak: 3500, id: "unit-water-bottle", isBaseUnit: true, isPurchaseUnit: true, status: "active", unitName: "Bottle" },
      { barcode: "", conversionQty: 12, costPriceLak: 42000, id: "unit-water-pack", isBaseUnit: false, isPurchaseUnit: true, status: "active", unitName: "Pack" },
      { barcode: "8851959132022", conversionQty: 24, costPriceLak: 84000, id: "unit-water-carton", isBaseUnit: false, isPurchaseUnit: true, status: "active", unitName: "Carton" },
    ],
    minStock: 48,
    expiryDate: "2027-01-04",
    lastMovementAt: "2026-06-13",
    daysWithoutSale: 0,
  },
  {
    id: "inv-lays-main",
    productId: "prd-lays-classic",
    warehouseId: "wh-main",
    imageKey: "snack",
    productNameLo: "ເລສ ລົດດັ້ງເດີມ",
    productNameEn: "Lay's Classic",
    barcode: "8850718811220",
    sku: "SNK-LAY-CLS-050",
    category: "Snacks",
    baseUnit: "Bag",
    quantity: 4,
    inventoryValueLak: 20000,
    lastPurchaseDate: "2026-06-01",
    productCode: "P-0003",
    supplierName: "ABC Trading",
    unitsSold30Days: 1200,
    units: [
      { barcode: "8850718811220", conversionQty: 1, costPriceLak: 5000, id: "unit-lays-bag", isBaseUnit: true, isPurchaseUnit: true, status: "active", unitName: "Bag" },
      { barcode: "", conversionQty: 12, costPriceLak: 60000, id: "unit-lays-box", isBaseUnit: false, isPurchaseUnit: true, status: "active", unitName: "Box" },
    ],
    minStock: 20,
    expiryDate: "2026-07-02",
    lastMovementAt: "2026-05-19",
    daysWithoutSale: 25,
  },
  {
    id: "inv-soap-backroom",
    productId: "prd-dishwashing-liquid",
    warehouseId: "wh-backroom",
    imageKey: "soap",
    productNameLo: "ນ້ຳຢາລ້າງຈານ",
    productNameEn: "Dishwashing Liquid",
    barcode: "8850006330181",
    sku: "HOU-SOAP-500",
    category: "Household",
    baseUnit: "Bottle",
    quantity: 62,
    inventoryValueLak: 744000,
    lastPurchaseDate: "2026-04-22",
    productCode: "P-0004",
    supplierName: "Lao Home Supplies",
    unitsSold30Days: 0,
    units: [
      { barcode: "8850006330181", conversionQty: 1, costPriceLak: 12000, id: "unit-soap-bottle", isBaseUnit: true, isPurchaseUnit: true, status: "active", unitName: "Bottle" },
      { barcode: "", conversionQty: 12, costPriceLak: 144000, id: "unit-soap-carton", isBaseUnit: false, isPurchaseUnit: true, status: "active", unitName: "Carton" },
    ],
    minStock: 12,
    lastMovementAt: "2026-04-22",
    daysWithoutSale: 52,
  },
  {
    id: "inv-yogurt-cold",
    productId: "prd-yogurt-cup",
    warehouseId: "wh-cold",
    imageKey: "cold",
    productNameLo: "ນົມສົ້ມ",
    productNameEn: "Yogurt Cup",
    barcode: "8853002411001",
    sku: "CLD-YOG-CUP-001",
    category: "Cold Goods",
    baseUnit: "Cup",
    quantity: 33,
    inventoryValueLak: 132000,
    lastPurchaseDate: "2026-06-11",
    productCode: "P-0005",
    supplierName: "Cold Fresh Laos",
    unitsSold30Days: 420,
    units: [
      { barcode: "8853002411001", conversionQty: 1, costPriceLak: 4000, id: "unit-yogurt-cup", isBaseUnit: true, isPurchaseUnit: true, status: "active", unitName: "Cup" },
      { barcode: "", conversionQty: 24, costPriceLak: 96000, id: "unit-yogurt-tray", isBaseUnit: false, isPurchaseUnit: true, status: "active", unitName: "Tray" },
    ],
    minStock: 30,
    expiryDate: "2026-06-21",
    lastMovementAt: "2026-06-11",
    daysWithoutSale: 1,
  },
];

export const mockStockMovements: StockMovement[] = [
  {
    id: "mov-001",
    productId: "prd-water-bottle",
    warehouseId: "wh-main",
    productName: "Drinking Water 500ml",
    sku: "DRK-WAT-BTL-500",
    movementType: "stock_in",
    quantity: 72,
    beforeQty: 54,
    afterQty: 126,
    note: "Manual mock stock in",
    createdBy: "Store Owner",
    createdAt: "2026-06-13 09:15",
  },
  {
    id: "mov-002",
    productId: "prd-pepsi-can",
    warehouseId: "wh-main",
    productName: "Pepsi Can",
    sku: "DRK-PEP-CAN-001",
    movementType: "adjustment",
    quantity: -6,
    beforeQty: 24,
    afterQty: 18,
    note: "Damaged cans",
    createdBy: "Manager",
    createdAt: "2026-06-12 18:40",
  },
  {
    id: "mov-003",
    productId: "prd-yogurt-cup",
    warehouseId: "wh-cold",
    productName: "Yogurt Cup",
    sku: "CLD-YOG-CUP-001",
    movementType: "count",
    quantity: 3,
    beforeQty: 30,
    afterQty: 33,
    note: "Stock count correction",
    createdBy: "Warehouse Staff",
    createdAt: "2026-06-11 20:05",
  },
  {
    id: "mov-004",
    productId: "prd-dishwashing-liquid",
    warehouseId: "wh-backroom",
    productName: "Dishwashing Liquid",
    sku: "HOU-SOAP-500",
    movementType: "transfer_in",
    quantity: 12,
    beforeQty: 50,
    afterQty: 62,
    note: "Transfer from supplier staging",
    createdBy: "Warehouse Staff",
    createdAt: "2026-06-08 14:20",
  },
];
