import type { Promotion } from "@/features/promotions/types";

export const mockPromotions: Promotion[] = [
  {
    id: "promo-drink-10",
    promotionCode: "PROMO-DRINK-10",
    promotionName: "Drink Weekend 10%",
    description: "Percentage discount for selected drink products during the weekend.",
    type: "percentage",
    startDate: "2026-06-14",
    endDate: "2026-06-30",
    priority: 10,
    applicableProductIds: ["prd-pepsi-can", "prd-water-bottle"],
    applicableCategoryIds: ["cat-drinks"],
    membershipLevels: ["Standard", "Silver", "Gold", "Platinum"],
    status: "active",
    discountPercent: 10,
    usageCount: 48,
    totalDiscountLak: 384000,
    totalSalesLak: 4224000,
  },
  {
    id: "promo-member-gold",
    promotionCode: "PROMO-MEMBER-GOLD",
    promotionName: "Gold Member Extra",
    description: "Member-only discount for Gold and Platinum customers.",
    type: "member_discount",
    startDate: "2026-06-01",
    endDate: "2026-07-15",
    priority: 20,
    applicableProductIds: [],
    applicableCategoryIds: ["cat-drinks", "cat-snacks"],
    membershipLevels: ["Gold", "Platinum"],
    status: "active",
    discountPercent: 5,
    usageCount: 23,
    totalDiscountLak: 215000,
    totalSalesLak: 4300000,
  },
  {
    id: "promo-buy2-water",
    promotionCode: "PROMO-BUY2-WATER",
    promotionName: "Buy 2 Water Get 1",
    description: "Buy two bottles of water and get one free.",
    type: "buy_x_get_y",
    startDate: "2026-06-10",
    endDate: "2026-06-25",
    priority: 30,
    applicableProductIds: ["prd-water-bottle"],
    applicableCategoryIds: [],
    membershipLevels: ["Standard", "Silver", "Gold", "Platinum"],
    status: "active",
    buyQuantity: 2,
    getQuantity: 1,
    usageCount: 61,
    totalDiscountLak: 183000,
    totalSalesLak: 549000,
  },
  {
    id: "promo-household-fixed",
    promotionCode: "PROMO-HOME-5000",
    promotionName: "Household 5,000 LAK Off",
    description: "Fixed amount discount for household cleaning products.",
    type: "fixed_amount",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    priority: 40,
    applicableProductIds: ["prd-dish-soap"],
    applicableCategoryIds: ["cat-household"],
    membershipLevels: ["Silver", "Gold", "Platinum"],
    status: "scheduled",
    discountAmountLak: 5000,
    usageCount: 0,
    totalDiscountLak: 0,
    totalSalesLak: 0,
  },
  {
    id: "promo-snack-combo",
    promotionCode: "PROMO-SNACK-COMBO",
    promotionName: "Snack Combo Set",
    description: "Combo price for snack and drink bundle.",
    type: "combo_set",
    startDate: "2026-05-01",
    endDate: "2026-05-31",
    priority: 50,
    applicableProductIds: ["prd-pepsi-can", "prd-lays-classic"],
    applicableCategoryIds: ["cat-snacks"],
    membershipLevels: ["Standard", "Silver", "Gold", "Platinum"],
    status: "expired",
    comboPriceLak: 15000,
    usageCount: 34,
    totalDiscountLak: 102000,
    totalSalesLak: 510000,
  },
];
