import type { PosCustomer, PosProduct, QrBank } from "@/features/pos/types";

export const mockPosProducts: PosProduct[] = [
  {
    id: "prd-water-bottle",
    barcode: "8851959132015",
    sku: "DRK-WAT-BTL-500",
    productCode: "WAT500",
    nameLo: "Drinking Water 500ml",
    nameEn: "Drinking Water 500ml",
    categoryName: "Drinks",
    imageKey: "water",
    unitName: "Bottle",
    priceLak: 6000,
    specialStudentPriceLak: 5000,
    stockQty: 126,
    isFavorite: true,
  },
  {
    id: "prd-pepsi-can",
    barcode: "8858998580011",
    sku: "DRK-PEP-CAN-001",
    productCode: "PEP-CAN",
    nameLo: "Pepsi Can",
    nameEn: "Pepsi Can",
    categoryName: "Drinks",
    imageKey: "pepsi",
    unitName: "Can",
    priceLak: 8000,
    stockQty: 18,
    isFavorite: true,
  },
  {
    id: "prd-noodles-cup",
    barcode: "8850100007001",
    sku: "FD-NDL-CUP-001",
    productCode: "NOODLE",
    nameLo: "Instant Noodles Cup",
    nameEn: "Instant Noodles Cup",
    categoryName: "Food",
    imageKey: "noodle",
    unitName: "Cup",
    priceLak: 9000,
    specialStudentPriceLak: 7000,
    stockQty: 44,
    isFavorite: true,
  },
  {
    id: "prd-lays-classic",
    barcode: "8850718811220",
    sku: "SNK-LAY-CLS-050",
    productCode: "LAY-CLS",
    nameLo: "Lay's Classic",
    nameEn: "Lay's Classic",
    categoryName: "Snacks",
    imageKey: "snack",
    unitName: "Bag",
    priceLak: 10000,
    stockQty: 4,
    lowStockThreshold: 8,
    isFavorite: true,
  },
  {
    id: "prd-yogurt-cup",
    barcode: "8853002411001",
    sku: "CLD-YOG-CUP-001",
    productCode: "YOG",
    nameLo: "Yogurt Cup",
    nameEn: "Yogurt Cup",
    categoryName: "Cold Goods",
    imageKey: "cold",
    unitName: "Cup",
    priceLak: 7000,
    stockQty: 33,
    expiryDate: "2026-06-22",
    isFavorite: true,
  },
  {
    id: "prd-milk-small",
    barcode: "8850123456789",
    sku: "CLD-MLK-SML-001",
    productCode: "MILK",
    nameLo: "UHT Milk",
    nameEn: "UHT Milk",
    categoryName: "Cold Goods",
    imageKey: "cold",
    unitName: "Box",
    priceLak: 6500,
    stockQty: 21,
    expiryDate: "2026-06-18",
    isFavorite: true,
  },
  {
    id: "prd-coffee-can",
    barcode: "8857777000101",
    sku: "DRK-COF-CAN-001",
    productCode: "COF-CAN",
    nameLo: "Ready Coffee",
    nameEn: "Ready Coffee",
    categoryName: "Drinks",
    imageKey: "coffee",
    unitName: "Can",
    priceLak: 9000,
    stockQty: 29,
    isFavorite: true,
  },
  {
    id: "prd-bread",
    barcode: "8852222000101",
    sku: "BKY-BRD-001",
    productCode: "BREAD",
    nameLo: "Sandwich Bread",
    nameEn: "Sandwich Bread",
    categoryName: "Bakery",
    imageKey: "bakery",
    unitName: "Pack",
    priceLak: 12000,
    stockQty: 16,
    expiryDate: "2026-06-19",
    isFavorite: true,
  },
  {
    id: "prd-ice-cream",
    barcode: "8853333000101",
    sku: "FRZ-ICE-001",
    productCode: "ICE",
    nameLo: "Ice Cream",
    nameEn: "Ice Cream",
    categoryName: "Frozen",
    imageKey: "cold",
    unitName: "Piece",
    priceLak: 10000,
    stockQty: 36,
    isFavorite: true,
  },
  {
    id: "prd-tissue",
    barcode: "8854444000101",
    sku: "HOU-TIS-001",
    productCode: "TISSUE",
    nameLo: "Tissue Pack",
    nameEn: "Tissue Pack",
    categoryName: "Household",
    imageKey: "paper",
    unitName: "Pack",
    priceLak: 11000,
    stockQty: 52,
    isFavorite: true,
  },
  {
    id: "prd-dish-soap",
    barcode: "8850006330181",
    sku: "HOU-SOAP-500",
    productCode: "SOAP",
    nameLo: "Dishwashing Liquid",
    nameEn: "Dishwashing Liquid",
    categoryName: "Household",
    imageKey: "soap",
    unitName: "Bottle",
    priceLak: 16000,
    stockQty: 62,
    isFavorite: true,
  },
  {
    id: "prd-carton-pack",
    barcode: "8850000000240",
    sku: "WHO-CAR-PACK-024",
    productCode: "CARTON",
    nameLo: "Carton Pack",
    nameEn: "Carton Pack",
    categoryName: "Wholesale",
    imageKey: "carton",
    unitName: "Carton",
    priceLak: 168000,
    stockQty: 12,
    isFavorite: true,
  },
  {
    id: "prd-eggs-pack",
    barcode: "8855555000101",
    sku: "FD-EGG-010",
    productCode: "EGGS",
    nameLo: "Eggs 10 Pack",
    nameEn: "Eggs 10 Pack",
    categoryName: "Food",
    imageKey: "food",
    unitName: "Pack",
    priceLak: 28000,
    stockQty: 9,
    lowStockThreshold: 10,
    isFavorite: true,
  },
  {
    id: "prd-expired-juice",
    barcode: "8856666000101",
    sku: "DRK-JCE-OLD",
    productCode: "JUICE",
    nameLo: "Orange Juice",
    nameEn: "Orange Juice",
    categoryName: "Drinks",
    imageKey: "juice",
    unitName: "Bottle",
    priceLak: 9500,
    stockQty: 3,
    expiryDate: "2026-06-01",
    lowStockThreshold: 6,
  },
  {
    id: "prd-shampoo",
    barcode: "8858888000101",
    sku: "PER-SHA-001",
    productCode: "SHAMPOO",
    nameLo: "Shampoo Sachet",
    nameEn: "Shampoo Sachet",
    categoryName: "Personal Care",
    imageKey: "soap",
    unitName: "Piece",
    priceLak: 3000,
    stockQty: 80,
  },
  {
    id: "prd-phone-card",
    barcode: "8859999000101",
    sku: "SVC-TOPUP-001",
    productCode: "TOPUP",
    nameLo: "Mobile Top Up",
    nameEn: "Mobile Top Up",
    categoryName: "Services",
    imageKey: "card",
    unitName: "Code",
    priceLak: 20000,
    stockQty: 999,
  },
];

export const mockPosCustomers: PosCustomer[] = [
  {
    id: "cus-somchai",
    customerCode: "CUS-001",
    name: "Somchai Phommachanh",
    phone: "02055550101",
    membershipNumber: "M-2026-001",
    membershipType: "Yearly",
    membershipStatus: "Active",
    membershipExpiry: "2026-12-31",
    pointsBalance: 420,
    discountPercent: 5,
  },
  {
    id: "cus-noy-student",
    customerCode: "CUS-002",
    name: "Noy Vongsa",
    phone: "02055550202",
    membershipNumber: "S-2026-018",
    membershipType: "Student",
    membershipStatus: "Active",
    membershipExpiry: "2026-09-30",
    pointsBalance: 95,
    studentIdNumber: "STU-88321",
    schoolName: "Vientiane Secondary School",
    studentCardUrl: "uploaded",
    discountPercent: 10,
  },
  {
    id: "cus-expired",
    customerCode: "CUS-003",
    name: "Khamla Retail",
    phone: "02055550303",
    membershipNumber: "M-2025-221",
    membershipType: "Monthly",
    membershipStatus: "Expired",
    membershipExpiry: "2026-01-31",
    pointsBalance: 12,
    discountPercent: 5,
  },
];

export const mockQrBanks: QrBank[] = [
  {
    id: "qr-bcel",
    bankName: "BCEL",
    accountName: "GO BOX Mini Mart",
    accountNumber: "010-12-99999999",
  },
  {
    id: "qr-jdb",
    bankName: "JDB",
    accountName: "GO BOX Mini Mart",
    accountNumber: "020-11-88888888",
  },
  {
    id: "qr-ldb",
    bankName: "LDB",
    accountName: "GO BOX Mini Mart",
    accountNumber: "030-22-77777777",
  },
];

export const mockPromotionBanners = [
  "Buy 2 Get 1 on selected drinks",
  "10% student member discount",
  "Member discount active today",
  "Combo snack + drink campaign",
];
